// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvEeugIDKNE9HFsMXW0U9yOQcTV5hsNpM',
    appId: '1:734921755027:web:f4761cd9e6862e1a774066',
    messagingSenderId: '734921755027',
    projectId: 'notes-flutter-project12',
    authDomain: 'notes-flutter-project12.firebaseapp.com',
    storageBucket: 'notes-flutter-project12.appspot.com',
    measurementId: 'G-5NNJSGJQPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuSCKH0YxCgvWqUPi8hG2J2ahTW9C9CUs',
    appId: '1:734921755027:android:f9b8a9875c91574a774066',
    messagingSenderId: '734921755027',
    projectId: 'notes-flutter-project12',
    storageBucket: 'notes-flutter-project12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIzto7hf_F5YRyhvHi49keTfIrFi47WS0',
    appId: '1:734921755027:ios:d9a46a693b57a034774066',
    messagingSenderId: '734921755027',
    projectId: 'notes-flutter-project12',
    storageBucket: 'notes-flutter-project12.appspot.com',
    iosClientId:
        '734921755027-des43p03k5inegi7ng94ce7cgfi6k42h.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIzto7hf_F5YRyhvHi49keTfIrFi47WS0',
    appId: '1:734921755027:ios:e7282920a1beb735774066',
    messagingSenderId: '734921755027',
    projectId: 'notes-flutter-project12',
    storageBucket: 'notes-flutter-project12.appspot.com',
    iosClientId:
        '734921755027-bs47kg68i689uv5460tq843fc2u77f63.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
